"""approval comment kind and creative version

Revision ID: 14801f0e80bc
Revises: f968f5591700
Create Date: 2026-10-02 19:23:35.638322

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "14801f0e80bc"
down_revision: str | None = "f968f5591700"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("approval_comments", sa.Column("creative_version", sa.Integer(), nullable=True))
    op.add_column(
        "approval_comments",
        sa.Column("kind", sa.String(length=30), server_default="comment", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("approval_comments", "kind")
    op.drop_column("approval_comments", "creative_version")
    # ### end Alembic commands ###
