"""topics: platform rules, strategy approval, platform fit (Sprint 5)

Revision ID: b6383c6848ab
Revises: b40db2a2a624
Create Date: 2026-10-02 16:58:21.128380

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b6383c6848ab"
down_revision: str | None = "b40db2a2a624"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_rules",
        sa.Column(
            "platform",
            sa.Enum(
                "linkedin",
                "x",
                "instagram",
                "facebook",
                name="platform",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "post_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "objectives",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "affinity_keywords",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("tone", sa.String(length=200), nullable=True),
        sa.Column("guidance", sa.Text(), nullable=True),
        sa.Column("max_length", sa.Integer(), nullable=True),
        sa.Column("hashtag_limit", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_platform_rules_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_rules")),
        sa.UniqueConstraint(
            "organization_id", "platform", name=op.f("uq_platform_rules_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_platform_rules_organization_id"),
        "platform_rules",
        ["organization_id"],
        unique=False,
    )
    op.add_column("content_strategies", sa.Column("rationale", sa.Text(), nullable=True))
    op.add_column(
        "content_strategies",
        sa.Column("source", sa.String(length=20), server_default="manual", nullable=False),
    )
    op.add_column("content_strategies", sa.Column("approved_by", sa.UUID(), nullable=True))
    op.add_column(
        "content_strategies", sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_content_strategies_approved_by_users"),
        "content_strategies",
        "users",
        ["approved_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "topic_candidates",
        sa.Column(
            "platform_fit",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "topic_candidates",
        sa.Column(
            "unsupported_claims",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.create_unique_constraint(
        op.f("uq_topic_candidates_organization_id"),
        "topic_candidates",
        ["organization_id", "trend_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_topic_candidates_organization_id"), "topic_candidates", type_="unique"
    )
    op.drop_column("topic_candidates", "unsupported_claims")
    op.drop_column("topic_candidates", "platform_fit")
    op.drop_constraint(
        op.f("fk_content_strategies_approved_by_users"), "content_strategies", type_="foreignkey"
    )
    op.drop_column("content_strategies", "approved_at")
    op.drop_column("content_strategies", "approved_by")
    op.drop_column("content_strategies", "source")
    op.drop_column("content_strategies", "rationale")
    op.drop_index(op.f("ix_platform_rules_organization_id"), table_name="platform_rules")
    op.drop_table("platform_rules")
    # ### end Alembic commands ###
