"""design brief source and asset notes

Revision ID: f968f5591700
Revises: 70ef6f103785
Create Date: 2026-10-02 18:30:26.826966

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f968f5591700"
down_revision: str | None = "70ef6f103785"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("creative_assets", sa.Column("note", sa.Text(), nullable=True))
    op.add_column(
        "design_briefs",
        sa.Column("source", sa.String(length=20), server_default="rules", nullable=False),
    )
    op.add_column(
        "design_briefs", sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("design_briefs", "submitted_at")
    op.drop_column("design_briefs", "source")
    op.drop_column("creative_assets", "note")
    # ### end Alembic commands ###
