"""post variants

Revision ID: 70ef6f103785
Revises: b6383c6848ab
Create Date: 2026-10-02 17:58:07.067204

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "70ef6f103785"
down_revision: str | None = "b6383c6848ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("variant_of_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_posts_variant_of_id"), "posts", ["variant_of_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_posts_variant_of_id_posts"),
        "posts",
        "posts",
        ["variant_of_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_posts_variant_of_id_posts"), "posts", type_="foreignkey")
    op.drop_index(op.f("ix_posts_variant_of_id"), table_name="posts")
    op.drop_column("posts", "variant_of_id")
    # ### end Alembic commands ###
